name: Terraform Apply

on:
  push:
    branches:
      - master
    paths:
      - "gcp/environments/**"
      - "gcp/modules/**"

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: gcp/environments/dev
        env:
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_bucket_name: ${{ secrets.DEV_BUCKET_NAME }}
